# Generated by Django 4.2.5 on 2023-09-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to='banner/images/')),
                ('category', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
