# Generated by Django 4.2.5 on 2023-09-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contact_fashiontrends_newsletter_showcase_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fashiontrends',
            options={'verbose_name_plural': 'Fashion Trends'},
        ),
    ]
