# Generated by Django 4.2.5 on 2023-09-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(default='abc', upload_to='Product/featured-images'),
            preserve_default=False,
        ),
    ]
