# Generated by Django 4.0.4 on 2023-09-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_cart_is_deleted_category_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
