# Generated by Django 4.0.4 on 2023-09-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_productimage_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
