# Generated by Django 4.0.4 on 2023-09-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price_of_product',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
