# Generated by Django 4.0.4 on 2023-09-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_cart_total_price_of_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type_discount', models.CharField(choices=[('amount', 'Amount'), ('percent', 'Percent')], max_length=100)),
                ('amount_or_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, to='shop.category')),
            ],
        ),
    ]
