# Generated by Django 4.0.4 on 2023-09-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_categories',
        ),
    ]
