# Generated by Django 4.0.4 on 2023-09-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_coupon_applicable_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
    ]
