# Generated by Django 4.0.4 on 2023-09-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_coupon_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='type_discount',
            new_name='discount_type',
        ),
    ]
