# Generated by Django 4.0.4 on 2023-09-29 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_order_orderstatus_payment_paymentmethod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_price_per_unit',
            new_name='order_total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_qty',
        ),
    ]
