# Generated by Django 4.0.4 on 2023-09-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_order_product_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_total_price',
        ),
    ]
