# Generated by Django 4.0.4 on 2023-09-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_remove_order_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total_price',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
