# Generated by Django 4.0.4 on 2023-09-29 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_productsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_unit',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.productsize'),
            preserve_default=False,
        ),
    ]
