# Generated by Django 4.0.4 on 2023-10-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_productvariant_delete_productsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
