# Generated by Django 4.0.4 on 2023-10-01 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_remove_product_stock_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
    ]
