# Generated by Django 4.0.4 on 2023-10-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_remove_productvariant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
