# Generated by Django 4.0.4 on 2023-10-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_productvariant_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_name',
        ),
    ]
