# Generated by Django 4.0.4 on 2023-10-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_remove_productvariant_variant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='variant_name',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'size')},
        ),
    ]
