# Generated by Django 4.0.4 on 2023-10-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_productvariant_variant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='variant_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
