# Generated by Django 4.0.4 on 2023-10-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_alter_productvariant_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
