# Generated by Django 4.0.4 on 2023-10-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_size',
            field=models.CharField(default='abc', max_length=150),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='shop.product'),
        ),
    ]
