# Generated by Django 4.0.4 on 2023-10-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_remove_order_total_price_orderitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='s', max_length=100),
            preserve_default=False,
        ),
    ]
