# Generated by Django 4.0.4 on 2023-10-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_alter_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderItems',
            new_name='order_items',
        ),
    ]
