# Generated by Django 4.0.4 on 2023-10-04 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_alter_cart_total_price_of_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('approved', 'Approved'), ('Rejected', 'Rejected'), ('cancelled', 'cancelled'), ('returned', 'Returned')], max_length=100)),
                ('ordered_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orderitem')),
            ],
        ),
    ]
