# Generated by Django 4.0.4 on 2023-10-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_ordermanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermanagement',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'cancelled'), ('returned', 'Returned')], max_length=100),
        ),
    ]
