# Generated by Django 4.0.4 on 2023-10-05 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_delete_wallethistory'),
        ('shop', '0045_alter_ordermanagement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermanagement',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('cancel', 'Cancel'), ('return', 'Return')], max_length=100),
        ),
        migrations.CreateModel(
            name='WalletHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_operation', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=100)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orderitem')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.wallet')),
            ],
            options={
                'verbose_name_plural': 'Wallet Histories',
            },
        ),
    ]
