# Generated by Django 4.0.4 on 2023-10-06 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_alter_ordermanagement_status_wallethistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
    ]
