# Generated by Django 4.0.4 on 2023-10-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_userreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallethistory',
            name='description',
            field=models.CharField(default='abc', max_length=150),
            preserve_default=False,
        ),
    ]
