# Generated by Django 4.0.4 on 2023-10-09 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_alter_wallethistory_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('amount', 'Amount'), ('percent', 'Percent')], max_length=100)),
                ('amount_or_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=50)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
    ]
