# Generated by Django 4.0.4 on 2023-10-09 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_discountcategoryoffer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscountCategoryOffer',
            new_name='CategoryOffer',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('discount_type', models.CharField(choices=[('amount', 'Amount'), ('percent', 'Percent')], max_length=100)),
                ('amount_or_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(to='shop.product')),
            ],
        ),
    ]
