# Generated by Django 4.0.4 on 2023-10-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_alter_productoffer_valid_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
