# Generated by Django 4.0.4 on 2023-10-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_alter_categoryoffer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
