# Generated by Django 4.0.4 on 2023-10-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_categoryoffer_applied_productoffer_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
