# Generated by Django 4.0.4 on 2023-10-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_alter_categoryoffer_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
