# Generated by Django 4.0.4 on 2023-10-05 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_wallet_wallethistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalletHistory',
        ),
    ]
