# Generated by Django 4.0.4 on 2023-10-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_referralamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referralamount',
            old_name='amount',
            new_name='new_user_amount',
        ),
        migrations.AddField(
            model_name='referralamount',
            name='referred_user_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
