# Generated by Django 4.0.4 on 2023-10-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_asgi', '0002_ordernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernotification',
            name='total_amount',
            field=models.CharField(default='1000', max_length=100),
            preserve_default=False,
        ),
    ]
